storage:
  location: anothertest
  host: localhost
  port: 5432
  db: fileuploader
  username: postgres
  password: postgres
  type: postgresql

spring:
  thymleaf:
    cache: false
  mvc:
    pathmatch:
      use-suffix-pattern: false
